- name: getting version
  include_vars:
    file: kafka-version.yml

- name: Getting Kafka .tar
  get_url:  
    url: http://ftp.unicamp.br/pub/apache/kafka/{{ kafka_version }}/kafka_2.11-{{ kafka_version }}.tgz
    dest: /tmp/kafka_{{ kafka_version }}.tgz

- name: Unzip .tar
  unarchive:
    src: /tmp/kafka_{{ kafka_version }}.tgz
    dest: /
    remote_src: yes

- name: rename folder
  shell: mv /kafka_{{ kafka_version }} /kafka