Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install python3 python3-pip python3-apt -yq
      sudo pip3 install ansible
    SHELL

    config.vm.provision "shell", inline: "cd /vagrant/ && ansible-playbook playbook-ansible.yml"

    config.vm.provision "shell", run: "always", inline: "cd /vagrant/ && bash check_status.sh"
    config.vm.provision "shell", run: "always", inline: "cd /vagrant/app && ./gocalculator"

    config.vm.network "forwarded_port", guest: 8080, host: 8080
  end