pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                dir('.') {
                 sh 'cd gatling-stress-test && mvn gatling:test'   
                 gatlingArchive()
                }
            }
        }
    }
}